// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("TomlProvider")>]
[<assembly: AssemblyProductAttribute("Toml.FSharp")>]
[<assembly: AssemblyDescriptionAttribute("FParsec TOML Parser for F#")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "TomlProvider"
    let [<Literal>] AssemblyProduct = "Toml.FSharp"
    let [<Literal>] AssemblyDescription = "FParsec TOML Parser for F#"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
